name: bmad-godot-game-dev
version: 1.0.0
short-title: Godot Game Dev Pack
description: Game Development expansion pack for BMad Method - Godot GDscript & C# focused
author: sjennings (Lum), based on BMAD Unity Game Dev expansion pack by pbean (PinkyD)
slashPrefix: BmadG
markdownExploder: true
qa:
  qaLocation: docs/qa
prd:
  prdFile: docs/prd.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: docs/architecture
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - docs/architecture/coding-standards.md
  - docs/architecture/tech-stack.md
  - docs/architecture/source-tree.md
  - docs/architecture/testing-strategy-and-standards.md
qaLoadAlwaysFiles:
  - docs/architecture/testing-strategy-and-standards.md
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/stories
